services:
  app:
    container_name: actions_oidc_proxy
    build: .
    # image: ghcr.io/ruial/actions-oidc-proxy:main
    ports:
      - "8000:8000"
    environment:
      - ACTIONS_OIDC_PROXY_OWNERS=ruial
